spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/stress
    username: root
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
      pool-name: HikariCP-Pool

mybatis:
  mapper-locations: classpath:mappers/*.xml

logging:
  level:
    root: info

server:
  port: 9091